/**
 * Multiple Choice Questions: "Pride and Prejudice" by Jane Austen
 * Source: Project Gutenberg (gutenberg.org) - Book #1342
 * Generated by Papersaurus AI Educational Tools
 * 
 * Each question has 5 options (A-E) with exactly one correct answer.
 * See answers.js for detailed explanations of all options.
 */

const questions = [
  {
    "id": 1,
    "question": "What is the famous opening line of Pride and Prejudice?",
    "options": {
      "A": "It was the best of times, it was the worst of times.",
      "B": "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
      "C": "Happy families are all alike; every unhappy family is unhappy in its own way.",
      "D": "There is no charm equal to tenderness of heart.",
      "E": "All the world is a stage, and all the men and women merely players."
    },
    "correctAnswer": "B"
  },
  {
    "id": 2,
    "question": "Why is it financially urgent for the Bennet sisters to marry well?",
    "options": {
      "A": "Their father has accumulated enormous gambling debts",
      "B": "Their mother has been disowned by her wealthy family",
      "C": "The Bennet estate is entailed to the male line, meaning the daughters cannot inherit it",
      "D": "A fire has destroyed the family's primary source of income",
      "E": "Mr. Bennet has secretly lost their fortune in bad investments"
    },
    "correctAnswer": "C"
  },
  {
    "id": 3,
    "question": "Which character represents 'pride' and which represents 'prejudice' in the novel's central relationship?",
    "options": {
      "A": "Jane represents pride and Bingley represents prejudice",
      "B": "Darcy represents prejudice and Elizabeth represents pride",
      "C": "Wickham represents pride and Lydia represents prejudice",
      "D": "Darcy is initially associated with pride and Elizabeth with prejudice, though both exhibit both traits",
      "E": "Mrs. Bennet represents pride and Mr. Collins represents prejudice"
    },
    "correctAnswer": "D"
  },
  {
    "id": 4,
    "question": "Who is Mr. Collins, and why is he significant to the Bennet family's situation?",
    "options": {
      "A": "He is a wealthy neighbor who wishes to buy the Bennet estate",
      "B": "He is a distant cousin who stands to inherit the Bennet estate through the entail",
      "C": "He is Elizabeth's former suitor who has returned from the navy",
      "D": "He is a solicitor hired to break the entail on the estate",
      "E": "He is Mr. Bennet's estranged brother who claims half the property"
    },
    "correctAnswer": "B"
  },
  {
    "id": 5,
    "question": "What literary device does Jane Austen most prominently use throughout Pride and Prejudice to critique social norms and characters?",
    "options": {
      "A": "Allegory and extended metaphor",
      "B": "Stream of consciousness narration",
      "C": "Irony and free indirect discourse",
      "D": "Magical realism and symbolism",
      "E": "Epistolary format exclusively"
    },
    "correctAnswer": "C"
  },
  {
    "id": 6,
    "question": "What event causes Elizabeth to fundamentally reassess her judgment of Mr. Darcy?",
    "options": {
      "A": "She overhears Darcy defending her to Miss Bingley",
      "B": "She receives Darcy's letter explaining his actions regarding Wickham and Jane",
      "C": "She discovers that Darcy secretly paid off her father's debts",
      "D": "Jane tells her that Darcy arranged her marriage to Bingley",
      "E": "She sees Darcy being kind to servants at a public ball"
    },
    "correctAnswer": "B"
  },
  {
    "id": 7,
    "question": "How does Wickham's elopement with Lydia threaten the entire Bennet family?",
    "options": {
      "A": "Wickham plans to claim the Bennet estate through the marriage",
      "B": "Lydia has stolen the family's savings to fund the elopement",
      "C": "The scandal of an unmarried elopement would ruin the reputation and marriage prospects of all the Bennet sisters",
      "D": "Mr. Bennet challenges Wickham to a duel, risking his life",
      "E": "Wickham is a convicted criminal, making the family guilty by association"
    },
    "correctAnswer": "C"
  },
  {
    "id": 8,
    "question": "In what year was Pride and Prejudice published, and during which historical period is it set?",
    "options": {
      "A": "1789, during the French Revolution",
      "B": "1847, during the Victorian era",
      "C": "1813, during the Regency era and Napoleonic Wars",
      "D": "1800, during the early Industrial Revolution",
      "E": "1830, during the reign of King William IV"
    },
    "correctAnswer": "C"
  },
  {
    "id": 9,
    "question": "What does Lady Catherine de Bourgh's visit to Elizabeth near the novel's end reveal about Austen's critique of the class system?",
    "options": {
      "A": "That the upper class is always gracious and welcoming to newcomers",
      "B": "That aristocratic authority and social rank do not equate to moral superiority, as Elizabeth rightly stands her ground",
      "C": "That Elizabeth secretly wishes to join the aristocracy at any cost",
      "D": "That Lady Catherine's objections are reasonable and well-founded",
      "E": "That marriages between different social classes always end in failure"
    },
    "correctAnswer": "B"
  },
  {
    "id": 10,
    "question": "Which character serves as a foil to Elizabeth Bennet by accepting Mr. Collins's proposal for practical rather than romantic reasons?",
    "options": {
      "A": "Jane Bennet",
      "B": "Lydia Bennet",
      "C": "Caroline Bingley",
      "D": "Charlotte Lucas",
      "E": "Georgiana Darcy"
    },
    "correctAnswer": "D"
  }
];

module.exports = { questions };
